#!/usr/bin/env python3
"""Daily iteration state update — Monday 2026-08-31.

Run summary
-----------
1. WEEKLY SWEEP (Monday). 7 active queries, 3 new PMIDs, 1 screened out.
2. FOUR OVERDUE WATCH ITEMS RESOLVED. Three had been stuck at pmid=PENDING
   since July with a next_recheck of 2026-08-07/13 that nobody ran. All three
   are now indexed and their PMIDs are recorded.
3. P3 #34 CLOSED — the "PMIDs above 42000000 are fabricated" rule is replaced
   by a runtime ceiling measured from PubMed (pmid_ceiling.py).
4. P3 #37 CLOSED — PMID 41986815 resolved.
5. THE RUN'S REAL FINDING: the credibility sweep, rewritten to scan markdown,
   found SIX misattributed PMIDs in RESEARCH_DOCTRINE.md and FOUR in
   Research_Findings_Summary.md. Every citation gate in this repo scans .py
   and only .py, so the governing document and the public summary had never
   been audited by anything.
6. The fixes were first written into the .md files and were WIPED by the next
   pipeline run, because Research_Findings_Summary.md is generated by
   add_citations.py. The new markdown gate caught the regression on the spot.
   Fixes now live in the generator.
"""
import json
import os
import shutil
from datetime import datetime

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATE = os.path.join(BASE, 'Results', 'agent_state.json')
TODAY = '2026-08-31'

with open(STATE, encoding='utf-8') as fh:
    state = json.load(fh)

shutil.copyfile(STATE, STATE + f'.bak_{TODAY}')

# ---------------------------------------------------------------------------
# 1. Weekly sweep intake. Everything enters UNVETTED: existence is verified,
#    claims are not. That distinction is the 2026-08-25 queue item's whole point.
# ---------------------------------------------------------------------------
NEW_PAPERS = {
    '42642774': {
        'title': ('The effect of CoQ10 supplementation on cardiovascular risk factors '
                  'in patients with prediabetes and type 2 diabetes mellitus: a '
                  'grade-assessed systematic review and dose-response meta-analysis.'),
        'journal': 'BMC pharmacology & toxicology', 'year': '2026',
        'design': 'SYNTHESIS (systematic review + dose-response meta-analysis, 20 RCTs)',
        'source_query': 'oxidative_stress_combination',
        'why_relevant': (
            'Bears directly on the suppressed oxidative_stress -> inflammation path '
            '(P1 item 2026-08-21). Reports a significant CRP reduction pooled across '
            'RCTs in prediabetes/T2D. NOTE it also found NO significant effect on '
            'malondialdehyde - the direct oxidative-stress marker - so it is not '
            'a clean confirmation and must not be summarised as one. CoQ10 is a '
            'supplement, not a repurposed generic drug; scope fit is a judgement '
            'call, flagged rather than assumed.'),
    },
    '42661296': {
        'title': ('B Lymphocytes in Latent Autoimmune Diabetes in Adults: From '
                  'Autoimmune Activation to Immunometabolic Heterogeneity and '
                  'Precision Therapeutic Perspectives.'),
        'journal': 'Diabetes/metabolism research and reviews', 'year': '2026',
        'design': 'NARRATIVE_REVIEW',
        'source_query': 'lada',
        'why_relevant': (
            'Gaps #1, #8, #10, #14. Describes GAD-antibody-stratified LADA endotypes. '
            'CAUTION: this is a narrative review, and the design audits of 2026-08-30 '
            'found the gap tiers are already carried disproportionately by narrative '
            'reviews (#2 and #6 are GOLD on 1 primary paper each). Adding another '
            'review to a LADA gap raises its paper count without raising its '
            'evidence. Ingest for context, do NOT let it promote a tier.'),
    },
    '42627334': {
        'title': ('beta-Cell Function and Diabetes Outcomes 1 Year After Stopping Oral '
                  'Baricitinib Immunotherapy for Type 1 Diabetes.'),
        'journal': 'Diabetes care', 'year': '2026',
        'design': 'PRIMARY (post-treatment follow-up of the randomised, double-blind, '
                  'placebo-controlled BANDIT trial; 88 of 91 completed week 96)',
        'source_query': 'found via watch-item recheck, NOT by the sweep queries',
        'why_relevant': (
            'HIGH VALUE AND THE SWEEP MISSED IT. Directly answers a durability '
            'question the hub tracks: baricitinib preserved C-peptide at week 72 '
            '(0.54 vs 0.38 pmol/mL, P=0.015) but NOT at week 96 (P=0.336), and the '
            'authors conclude durable benefit likely requires continuous treatment. '
            'Also reports an age split: adults (n=28) fully preserved beta-cell '
            'function after stopping, children (n=32) lost 0.09 pmol/mL (P=0.022). '
            'Research_Findings_Summary lists baricitinib/BARICADE as BRONZE with '
            '"Phase 2 data promising" - that framing now needs the waning result '
            'beside it. Queued.'),
    },
    '42283716': {
        'title': ('Extended Follow-up of Type 1 Diabetes Immunotherapy Trial '
                  'Participants Suggests Benign Side Effect Profile.'),
        'journal': 'Diabetes care', 'year': '2026',
        'design': 'PRIMARY (pooled long-term follow-up across 14 randomised trials; '
                  '47% participation, 209-473 responses per question, self-reported)',
        'source_query': 'watch_items_pending_pmid resolution',
        'why_relevant': (
            'Resolves watch item logged 2026-07-30 (Diabetes Care 2026;49(8):1428), '
            'DOI 10.2337/dc26-0632. Supports the teplizumab long-term follow-up path. '
            'CAVEAT TO CARRY: outcomes are SELF-REPORTED and 53% of eligible '
            'participants did not join. "No differences" here is absence of a '
            'detected signal in a partially-participating self-report cohort, not '
            'demonstrated safety, and must never be restated as the latter.'),
    },
    '41978270': {
        'title': ('Characterization of NLRP3 Inflammasome-Associated Hub Genes in the '
                  'Progression of Diabetic Nephropathy.'),
        'journal': 'Immunity, inflammation and disease', 'year': '2026',
        'design': 'BIOINFORMATICS (GEO GSE142025/GSE96804 hub-gene analysis)',
        'source_query': 'watch_items_pending_pmid resolution',
        'why_relevant': (
            'Resolves watch item logged 2026-07-21 (DOI 10.1002/iid3.70424), PENDING '
            'for 41 days. NOTE the open P2 question from 2026-08-25 applies squarely: '
            'a bioinformatics hub-gene analysis contains no patient outcome, so '
            'whether it counts as corpus evidence is exactly the undecided item.'),
    },
    '42196240': {
        'title': ('NLRP3 Inflammasome Inhibition Attenuates Diabetic Kidney Injury via '
                  'the Suppression of Ferroptosis: Mechanistic Insights from In Vivo '
                  'and In Vitro Models.'),
        'journal': 'International journal of molecular sciences', 'year': '2026',
        'design': 'PRECLINICAL (STZ diabetic WT + NLRP3-KO mice; HG HK-2 cells + siNLRP3)',
        'source_query': 'watch_items_pending_pmid resolution',
        'why_relevant': (
            'Resolves watch item logged 2026-07-21 (DOI 10.3390/ijms27104257). '
            'Mouse and cell work only. Does NOT close the standing gap (P4 '
            '2026-08-17) between NLRP3 suppression and renal HARD endpoints in '
            'humans; it is more preclinical evidence on the side that already had '
            'plenty.'),
    },
}

for pmid, meta in NEW_PAPERS.items():
    if pmid in state['papers']:
        continue
    state['papers'][pmid] = {
        'status': 'UNVETTED',
        'pmid_verified': True,
        'claims_checked': False,
        'issues_found': [],
        'title': meta['title'],
        'journal': meta['journal'],
        'year': meta['year'],
        'design': meta['design'],
        'added_date': TODAY,
        'added_by': 'weekly sweep / watch-item resolution 2026-08-31',
        'source_query': meta['source_query'],
        'vetting_notes': meta['why_relevant'],
        'claims_checked_method': (
            'existence + title/journal/year confirmed via eutils esummary '
            f'{TODAY}; CLAIMS NOT YET VETTED'),
    }

# ---------------------------------------------------------------------------
# 2. Screened out at intake.
# ---------------------------------------------------------------------------
state.setdefault('screened_out', {})[TODAY] = {
    'pmids': ['42634756'],
    'reason': (
        'Single-patient case report: "Double autoimmune endocrinopathies: concurrent '
        'presentation of latent autoimmune diabetes in adults and Graves disease" '
        '(JCEM Case Reports 2026). Returned by the `lada` sweep query, on topic, and '
        'deliberately NOT ingested. n=1 supplies no rate, no comparator and no effect '
        'size, so it can only inflate the paper count of the LADA gaps without '
        'changing what they know - the exact failure mode the 2026-08-30 design '
        'audits found. Recorded rather than discarded so the decision is reviewable.'),
}

# ---------------------------------------------------------------------------
# 3. Watch items: three of four resolved.
# ---------------------------------------------------------------------------
RESOLVED_WATCH = {
    '10.1002/iid3.70424': '41978270',
    '10.3390/ijms27104257': '42196240',
}
for item in state.get('watch_items_pending_pmid', []):
    doi = item.get('doi')
    if doi in RESOLVED_WATCH:
        item['pmid'] = RESOLVED_WATCH[doi]
        item['status'] = 'RESOLVED_INDEXED'
        item['last_rechecked'] = TODAY
        item['resolution_note'] = (
            f'PubMed indexed it. Found by DOI search [aid] on {TODAY}, after the '
            '2026-08-07 recheck date passed unworked for 24 days. Ingested UNVETTED.')
    elif 'TrialNet' in str(item.get('authors', '')):
        item['pmid'] = '42283716'
        item['doi'] = '10.2337/dc26-0632'
        item['status'] = 'RESOLVED_INDEXED'
        item['last_rechecked'] = TODAY
        item['resolution_note'] = (
            f'PMID 42283716, Diabetes Care 2026 Aug 1. Found {TODAY}; the 2026-08-13 '
            'recheck date had passed unworked for 18 days.')

state.setdefault('doctrine_notes', {})['watch_item_recheck_dates_are_not_self_executing'] = {
    'date': TODAY,
    'note': (
        'Three watch items carried next_recheck dates of 2026-08-07 and 2026-08-13 '
        'and sat untouched for 18-41 days while eight daily runs went past them. All '
        'three resolved on the first attempt with a single DOI query. A date field '
        'that nothing reads is a reminder nobody receives. RECOMMENDED: fold '
        'watch_items_pending_pmid into the work queue proper so overdue items surface '
        'the way queue items do, rather than living in a side list.'),
}

# ---------------------------------------------------------------------------
# 4. Close what was actually finished.
# ---------------------------------------------------------------------------
CLOSED = {
    'REPLACE THE HARDCODED FABRICATION THRESHOLD': (
        'CLOSED 2026-08-31. pmid_ceiling.py measures the ceiling from PubMed at '
        'runtime and caches it for 7 days; audit_impossible_pmids.py consumes it and '
        'is wired into run_quality_improvements.py as `credibility`. Live ceiling '
        'measured 42,669,647 - the hardcoded 42,000,000 was 669,647 PMIDs stale, '
        'about five months of issuance. Flag line is ceiling+250,000; the repo\'s '
        'highest PMID is 42,608,595, leaving 311,052 of headroom. The margin absorbs '
        'cache staleness ONLY; existence is still proved by verify_pmids.py.'),
    'RESOLVE PMID 41986815': (
        'CLOSED 2026-08-31. Diabetologia 2026 Jul, "Multi-tissue multi-omics '
        'integration reveals tissue-specific pathways, gene networks and drug '
        'candidates for type 1 diabetes." Design: computational integration of human '
        'T1D GWAS with tissue-specific regulatory data, key-driver genes validated in '
        'NOD mice, drug-repositioning predictions tested against OneFlorida+ EMR. '
        'Species: human genomic data + mouse validation; no human n, because there is '
        'no human intervention. Relevant to the drug-repurposing gaps as a '
        'HYPOTHESIS-GENERATING source - its drug candidates are predictions with EMR '
        'support, not trial results, and must not be cited as efficacy.'),
}
for item in state['work_queue']:
    for key, note in CLOSED.items():
        if key.lower() in item.get('target', '').lower():
            item['status'] = 'CLOSED'
            item['closed'] = TODAY
            item['closing_note'] = note

state['closed_queue_items'] = state.get('closed_queue_items', [])
state['closed_queue_items'].extend(
    item for item in state['work_queue'] if item.get('closed') == TODAY)
state['work_queue'] = [item for item in state['work_queue']
                       if item.get('closed') != TODAY]

# ---------------------------------------------------------------------------
# 5. New findings -> new queue items.
# ---------------------------------------------------------------------------
NEW_ITEMS = [
    {
        'priority': 1,
        'type': 'user_action_required',
        'added': TODAY,
        'target': (
            'HUMAN CALL, AND THIS ONE CONSOLIDATES SEVEN OTHERS. The P1 queue has '
            'held 6-7 untouched HUMAN CALL items since 2026-08-20 and each daily run '
            'has added another rather than resolving any. Read together they are not '
            'seven questions, they are ONE question asked seven ways: SHOULD A '
            'RANKING, A TIER OR A HEADLINE COUNT BE DERIVED FROM HOW MANY CITATIONS '
            'EXIST, OR FROM WHAT DESIGN THEY CARRY? '
            '(a) 2026-08-20 dose_response: 192 of 414 headline data points are bare '
            'dose labels. (b) 2026-08-21: 29 of 47 paths went hollow when regex '
            'artifact was removed. (c) 2026-08-22/28/29 verapamil: the #4 and #5 '
            'paths rest on a PROTOCOL while a real RCT (36826844, CLVer) sits unused '
            'in the library. (d) 2026-08-27: one insulin-pricing review carries 91 '
            'claims. (e) 2026-08-29: the Bayesian prior is 62.3% discordant with '
            'study design. (f) 2026-08-30: three GOLD/SILVER gaps rest on one primary '
            'paper each. (g) 2026-08-31 (today): RESEARCH_DOCTRINE.md\'s own GOLD '
            'exemplar counted three documents that all comment on ONE 12-patient '
            'phase 1-2 trial as three independent sources. '
            'ANSWER (g) FIRST. It is the cheapest and it governs the rest: the '
            'doctrine defines GOLD as "three independent sources", and today showed '
            'the definition permits counting one study three times. Fix the '
            'definition - require independent DATA, not independent documents - and '
            '(a) through (f) mostly follow from it instead of needing six separate '
            'rulings. A single ruling on the definition unblocks the queue; seven '
            'separate rulings is why it has not moved in eleven days.'),
    },
    {
        'priority': 1,
        'type': 'fix_pipeline',
        'added': TODAY,
        'target': (
            'AUDIT THE REMAINING GENERATED MARKDOWN THE SAME WAY. Today proved the '
            'gates had a whole file class in their blind spot: verify_pmids.py:44 and '
            'audit_prose_citation_titles.py:349 both scan .py only, so '
            'RESEARCH_DOCTRINE.md and Research_Findings_Summary.md had never been '
            'checked by anything and held 10 misattributed PMIDs between them. '
            'audit_markdown_citations.py now covers repo root, docs/ and Notes/. NOT '
            'yet covered: Analysis/Results/*.md (excluded as historical record - '
            'verify that is still true, since some are linked from dashboards) and '
            'any .md under Papers/. Also confirm no OTHER generated markdown exists '
            'whose generator holds the real text, the way add_citations.py holds '
            'Research_Findings_Summary.md.'),
    },
    {
        'priority': 2,
        'type': 'analysis',
        'added': TODAY,
        'target': (
            'RE-FRAME BARICITINIB ON THE STRENGTH OF PMID 42627334 (Diabetes Care '
            '2026, BANDIT post-treatment follow-up). Research_Findings_Summary '
            'currently lists baricitinib/BARICADE as BRONZE with "Phase 2 data '
            'promising; Phase 3 not yet enrolled". The new paper reports that the '
            'benefit WANES: C-peptide significantly greater at week 72 (0.54 vs 0.38 '
            'pmol/mL, P=0.015) but not at week 96 (P=0.336), no differences in insulin '
            'dose, HbA1c or CGM measures during follow-up, and the CD8+ effector '
            'memory changes seen at week 48 had resolved by week 96. The authors '
            'conclude durable benefit likely requires continuous treatment. There is '
            'also an age split worth carrying: adults (n=28) fully preserved '
            'beta-cell function after stopping, children (n=32) declined (P=0.022) - '
            'note this is POST HOC. "Promising" without "wanes off-treatment" is the '
            'kind of half-summary this repo keeps catching elsewhere.'),
    },
    {
        'priority': 2,
        'type': 'vet_papers_batch',
        'added': TODAY,
        'target': (
            'VET THE 6 PAPERS INGESTED 2026-08-31. Existence and metadata are '
            'confirmed; CLAIMS are not. Highest value first: 42627334 (BANDIT '
            'follow-up - read the durability numbers against what the hub currently '
            'says about baricitinib), 42283716 (TrialNet safety - confirm the '
            'self-report and 47%-participation caveats travel with any use of it), '
            '42642774 (CoQ10 meta-analysis - note it found CRP down but '
            'malondialdehyde unchanged; do not let it be summarised as an '
            'oxidative-stress win), then 42661296, 41978270, 42196240.'),
    },
    {
        'priority': 3,
        'type': 'fix_pipeline',
        'added': TODAY,
        'target': (
            'FOLD watch_items_pending_pmid INTO THE WORK QUEUE. Three items carried '
            'next_recheck dates of 2026-08-07/13 and were passed over by eight '
            'consecutive daily runs, then all three resolved on the first attempt '
            'with one DOI query each. The side list has no surfacing mechanism: '
            'nothing reads the date. Either give it one or move the items into '
            'work_queue where the priority ordering already does that job.'),
    },
    {
        'priority': 3,
        'type': 'analysis',
        'added': TODAY,
        'target': (
            'DECIDE WHETHER CoQ10 (PMID 42642774) IS IN SCOPE. The hub is about '
            'repurposing GENERIC DRUGS; CoQ10 is a dietary supplement. Its 20-RCT '
            'meta-analysis is the strongest new evidence touching the suppressed '
            'oxidative_stress -> inflammation path, which makes it tempting, and it '
            'is a category the corpus has no rule for. Note the result is mixed on '
            'its own terms: significant reductions in triglycerides, FBS, HbA1c, '
            'HOMA-IR and CRP, but NO significant effect on malondialdehyde, total '
            'cholesterol, LDL or blood pressure. A path about oxidative stress '
            'supported by a trial that failed to move the oxidative-stress marker '
            'needs that stated, not smoothed over.'),
    },
]
state['work_queue'] = NEW_ITEMS + state['work_queue']

# ---------------------------------------------------------------------------
# 6. Topic checks + run history.
# ---------------------------------------------------------------------------
state.setdefault('topic_checks', {})['weekly_sweep_2026-08-31'] = {
    'date': TODAY,
    'queries_run': 7,
    'new_pmids': 3,
    'screened_out': 1,
    'per_query': {
        'oxidative_stress_combination': '1 new (42642774)',
        'lada': '2 new (42661296 ingested; 42634756 screened out as n=1 case report)',
        'islet_transplant_outcomes': '0 in 7-day window',
        'nlrp3_dkd': '0 in 7-day window',
        'drug_repurposing': '0 in 7-day window',
        'verapamil_t1d': '0 in 7-day window',
        'sglt2_colchicine_combination': '0 in 7-day window',
    },
    'note': (
        'FIVE OF SEVEN QUERIES RETURNED NOTHING, and the most valuable paper of the '
        'run (42627334, BANDIT follow-up in Diabetes Care) was NOT found by any of '
        'them - it surfaced while rechecking an unrelated watch item. It published '
        '2026-08-21, outside the 7-day reldate window, and no active query covers '
        'baricitinib or JAK inhibition. Two structural gaps, both worth fixing: the '
        '7-day window silently drops anything missed in a skipped week, and the query '
        'set has no immunotherapy-durability term.'),
}

state['run_history'].append({
    'date': TODAY,
    'day': 'Monday',
    'papers_added': 6,
    'papers_screened_out': 1,
    'watch_items_resolved': 3,
    'queue_items_closed': 2,
    'new_gates': 3,
    'miscitations_found': 10,
    'miscitations_repaired': 10,
    'changes_pushed': False,
    'summary': (
        'Mon 2026-08-31 - THE DOCUMENT THAT DEFINES THIS PROJECT\'S CITATION STANDARD '
        'CONTAINED SIX MISATTRIBUTED CITATIONS, AND NO GATE COULD SEE THEM. '
        '(1) THE P1 QUEUE WAS AGAIN LEFT TO THE HUMAN, but not merely deferred: a '
        'consolidating item was added arguing the seven standing HUMAN CALLs are one '
        'question - count-derived versus design-derived authority - and that answering '
        'the doctrine-definition instance first subsumes most of the rest. Eleven days '
        'of adding an item a day without resolving one is the thing to stop. '
        '(2) THE CREDIBILITY SWEEP WAS REBUILT AND IMMEDIATELY EARNED ITS KEEP. The '
        'task file\'s "PMIDs above 42000000 are fabricated" rule was measured stale by '
        '669,647 - the live ceiling is 42,669,647 - and replaced with a runtime '
        'measurement. Rewriting the sweep to read .md as well as .py exposed the '
        'blind spot: verify_pmids.py:44 and audit_prose_citation_titles.py:349 both '
        'scan .py ONLY, so no gate had ever read the markdown. '
        '(3) RESEARCH_DOCTRINE.md CARRIED SIX MISATTRIBUTED PMIDs INSIDE ITS OWN '
        'WORKED EXAMPLES OF CORRECT CITATION. Its "PMID-Verified (Strongest)" exemplar '
        'sourced the $237bn US diabetes cost to 35912345, a halide-perovskite '
        'solar-cell paper (real figure, real PMID, wrong pairing, and attributed to '
        'the CDC in 2023 when it is ADA data for 2017). Its correct-citation-FORMAT '
        'exemplar pointed at 38234567, a RETRACTED ginsenoside renal-ischaemia study. '
        'Its GOLD-tier exemplar cited 37234567 (HPV self-sampling in Minnesota) and '
        '37456789 (mesoscopic cell migration) as the NEJM zimislecel trial and a '
        'Lancet commentary. Every one resolves on PubMed, which is exactly why five '
        'months of runs walked past them. '
        '(4) THE GOLD EXEMPLAR WAS ALSO WRONG ON THE SCIENCE, which matters more than '
        'the identifiers. Re-sourced to the real trial (40544428, NEJM 2025) it is a '
        'phase 1-2 study of 14 patients with interim, non-prespecified analyses and '
        'two deaths - not the "Phase 3" the doctrine claimed - and the two '
        'confirmatory sources are both commentary ON that trial. Counting them as '
        'independent confirmation counts 12 patients three times. Re-tiered SILVER, '
        'aligning with 10_Questions_Self_Audit.md which had rated the same claim '
        'SILVER all along: two governing documents had disagreed about the tier of '
        'the same claim and nothing noticed. '
        '(5) Research_Findings_Summary.md HELD FOUR MORE. A GOLD-rated icodec claim '
        'cited 37356449, a Lancet health-policy piece with no icodec data, while the '
        'three ONWARDS trials that actually justify GOLD went uncited. Orforglipron '
        'cited 37385277, a Lancet Comment about SEMAGLUTIDE. Dorzagliatin cited a 2025 '
        'preclinical PK-PD paper as "Nature Medicine 2022". Retatrutide cited the '
        'right paper with the wrong journal, wrong year, wrong NCT and a weight-loss '
        'figure (28.7% at 68 weeks) that does not appear in it - the trial ran 48 '
        'weeks and reported 24.2%. All four re-sourced against the live API. '
        '(6) THE FIRST ROUND OF FIXES WAS SILENTLY REVERTED AND THE NEW GATE CAUGHT '
        'IT. Research_Findings_Summary.md is GENERATED by add_citations.py; editing '
        'the .md was undone by the next pipeline run. The markdown gate went red on '
        'the regenerated file within the same run. Fixes moved into the generator. '
        'This is the strongest evidence the gate works: it caught a regression that '
        'no human was watching for. '
        '(7) THE GATE ITSELF REPRODUCED THE REPO\'S FAVOURITE MISTAKE ON DRAFT ONE - '
        'flagging 71 of 73 sites, a 97% false-positive rate, by scoring citations '
        'against title claims the text never made. Same failure as '
        'audit_prose_citation_titles.py (249 spurious, 2026-08-26) and '
        'audit_gap_evidence_design.py (2026-08-30). Fixed by requiring a marked-up '
        'title span adjacent to the identifier; a corpus-derived journal lexicon was '
        'then tried, measured (235 tokens, 14 findings, 14 of them false because '
        '"drug" and "kidney" appear in journal names), and REJECTED in favour of a '
        'small hand-verified alias list. Final: 0 of 61 flagged. '
        '(8) A 0-FINDING GATE PROVES NOTHING WHEN THE SAME RUN REPAIRED EVERYTHING IT '
        'HUNTS, so test_markdown_citation_gate.py pins it against the verbatim '
        'pre-repair text: 4 defects it must catch, 4 correct citations the draft '
        'wrongly flagged that it must not. 8/8. The fixture caught a real hole while '
        'being written - the JAMA-for-NEJM error survived the year check because '
        'YEAR_SLACK=1 and the years were 2024 vs 2023, so a journal-contradiction '
        'test was added scoped to the bracketed citation record. '
        '(9) HOUSEKEEPING. Weekly sweep: 3 new PMIDs, 1 screened out as an n=1 case '
        'report. Three watch items that had been PENDING for 18-41 days past their '
        'recheck dates all resolved on the first DOI query - the recheck dates are '
        'written but nothing reads them, so a queue item was filed to fold them in. '
        'PMID 41986815 resolved (P3 #37). The most valuable new paper, 42627334 '
        '(BANDIT: baricitinib\'s beta-cell benefit WANES within 48 weeks of stopping), '
        'was found by accident, not by the sweep - no active query covers '
        'immunotherapy durability. All 63 pipeline scripts green.'),
})

state['last_run'] = TODAY
state['last_updated'] = TODAY
state['last_sweep'] = TODAY

with open(STATE, 'w', encoding='utf-8') as fh:
    json.dump(state, fh, indent=2, ensure_ascii=False)

print(f'State saved {datetime.now().isoformat()}')
print(f"  papers: {len(state['papers'])}")
print(f"  queue : {len(state['work_queue'])} open, "
      f"{len(state['closed_queue_items'])} closed")
print(f"  runs  : {len(state['run_history'])}")
