#!/usr/bin/env python3
"""Does every published ABSENCE claim declare the search that produced it?

WHY THIS EXISTS
---------------
An absence claim - "zero publications", "has never been tested", "no study has
measured" - is the only kind of claim in this repo that is generated by finding
NOTHING. Every other claim points at a PMID that either supports it or does
not, and fourteen citation gates check exactly that. A claim backed by an empty
result set has no citation to check, so all fourteen are silent on the claims
that are easiest to get wrong.

They are easy to get wrong because an empty result set is a fact about a QUERY,
not about the world, and the two get written down as if they were the same
thing. Three findings, all the same shape:

  2026-09-05, Gap #3. Every recorded sweep was bounded to 2020+. The published
  claim was "insulin resistance is UNMEASURED in islet transplant recipients".
  Re-run all-time, PubMed returns PMID 24085506 (JCEM 2013) and PMID 24691031
  (AJP-Endo 2014), both human primary studies measuring exactly that endpoint.
  No date-bounded sweep could ever have seen them.

  2026-09-06, Treg x diabetic neuropathy. build_treg_neuropathy.py published
  "Evidence connecting Tregs + diabetic neuropathy = zero" and "Treg-based
  therapy has never been tested for diabetic neuropathy". All-time the
  intersection returns 7 records, two of them preclinical interventions acting
  THROUGH Tregs: PMID 42698953 (Biomater Res, 2026-09-04, IL-2 nanoplatform in
  a DPN mouse model, FoxP3 knockdown confirms Treg dependence) and PMID
  39084449 (2024). The CLINICAL gap is real. The unqualified claim was not.

  2026-09-06, computational screening x islet transplant. The published gap
  table carries pair_count 0 and the sentence "Computational drug screening has
  not been applied here." All-time the intersection returns 7 records - so the
  COUNT is wrong - but on reading titles and pubtypes none is a drug screen for
  islet protection, so the SENTENCE is right. Right conclusion, wrong evidence,
  and nothing in the pipeline could tell those apart.

The rule that separates all three: an absence claim must be stated at the scope
of the search that produced it. "Zero 2020-2026" is a finding. "Zero" is an
extrapolation. "Never tested" is a claim about all of history and all study
designs; "no human trial" is a claim a bounded search can actually support.

WHAT THIS GATE ASSERTS
----------------------
For each absence claim found in generated output, a SCOPE QUALIFIER must appear
within SCOPE_WINDOW characters. Any one of these qualifies:

    a date or range          "2020-2026", "as of 2026-09-06", "since 2020"
    an explicit all-time     "all-time", "all time", "unbounded"
    a design restriction     "clinical", "in humans", "human trial",
                             "randomised/randomized", "no trial"
    a named search           "PubMed search", "re-run", "query returns"

    UNSCOPED_ABSENCE   an absence claim with no qualifier in range. The reader
                       cannot tell whether the search covered 6 years or 60,
                       abstracts or full text, humans or mice.

This gate does NOT check whether a claim is true - it cannot, offline. It
checks whether the claim says enough for a reader to know what would falsify
it. That is the property all three findings above were missing.

Scope: generated dashboards and reports under docs/ and Dashboards/, which is
what a reader sees. Hand-written .md at the repo root is out of scope; it is
prose by a human, not output asserted by a pipeline.

Exit codes: 0 clean, 1 findings.
"""
import json
import os
import re
import sys
from datetime import date

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(SCRIPT_DIR)
ROOT = os.path.dirname(BASE)
REPORT = os.path.join(BASE, 'Results', 'absence_claim_scope_audit.json')

SCAN_DIRS = ['docs', 'Dashboards']
SCAN_EXT = ('.html', '.md')

# How far around the claim a qualifier may sit. Wide enough for a following
# sentence or a source-note line, narrow enough that an unrelated date
# elsewhere on a long dashboard page does not launder the claim.
SCOPE_WINDOW = 420

ABSENCE_PATTERNS = [
    r'\bzero\s+(?:publications?|studies|trials|papers|records)\b',
    r'\bno\s+(?:published\s+)?(?:study|studies|trial|trials|publication|publications|data|evidence)\s+'
    r'(?:has|have|exists?|report|reports|measur\w*|address\w*|appl\w*|examin\w*)\b',
    r'\b(?:has|have)\s+never\s+been\s+\w+',
    r'\b(?:has|have)\s+not\s+been\s+'
    r'(?:studied|measured|reported|examined|applied|investigated|tested|evaluated|explored)\b',
    r'\bremains?\s+unmeasured\b',
    r'\bis\s+unmeasured\b',
    # "been" is REQUIRED here. Without it this pattern fired on
    # LADA_Prevalence.html's "85-90% Undiagnosed LADA (misclassified as T2D,
    # never tested)" - a statement about PATIENTS not receiving an antibody
    # test, which is the dashboard's actual subject and not a claim about the
    # literature at all. An absence-claim gate that flags clinical
    # under-testing is measuring the wrong noun.
    r'\bnever\s+been\s+(?:systematically\s+)?(?:evaluated|tested|studied|measured)\b',
    r'\b(?:evidence|publications?|studies)\s*(?:=|:)\s*zero\b',
    r'\bnot\s+a\s+single\s+(?:study|trial|publication)\b',
]

QUALIFIER_PATTERNS = [
    r'\b(?:19|20)\d{2}\s*(?:-|–|—|to|through)\s*(?:19|20)\d{2}\b',   # 2020-2026
    r'\b(?:19|20)\d{2}/\d{2}/\d{2}\b',                               # 2020/01/01
    r'\bas of\s+(?:19|20)\d{2}\b',
    r'\bsince\s+(?:19|20)\d{2}\b',
    r'\ball[-\s]time\b',
    r'\bunbounded\b',
    r'\bre-?run\s+\d{4}-\d{2}-\d{2}\b',
    r'\b(?:PubMed|MEDLINE)\s+(?:search|query|sweep)\b',
    r'\bquery\s+returns?\b',
    r'\bclinical(?:ly)?\b',
    r'\bin\s+humans?\b',
    r'\bhuman\s+(?:trial|stud|data)\w*\b',
    r'\brandomi[sz]ed\b',
    r'\bpreclinical\b',
    r'\bscope\s+check\b',
]

ABSENCE_RE = [re.compile(p, re.IGNORECASE) for p in ABSENCE_PATTERNS]
QUALIFIER_RE = [re.compile(p, re.IGNORECASE) for p in QUALIFIER_PATTERNS]
TAG_RE = re.compile(r'<[^>]+>')
WS_RE = re.compile(r'\s+')
COMMENT_RE = re.compile(r'<!--.*?-->', re.DOTALL)


def visible_text(raw, is_html):
    """Reader-visible text only.

    HTML comments are stripped FIRST and deliberately: a correction note in a
    comment explains the fix to a maintainer and is invisible to the reader, so
    it must not be able to satisfy the scope requirement for the reader-facing
    sentence next to it.
    """
    if is_html:
        raw = COMMENT_RE.sub(' ', raw)
        raw = re.sub(r'<(script|style)\b.*?</\1>', ' ', raw,
                     flags=re.DOTALL | re.IGNORECASE)
        raw = TAG_RE.sub(' ', raw)
    return WS_RE.sub(' ', raw)


def has_qualifier(text):
    return any(r.search(text) for r in QUALIFIER_RE)


def scan_file(path, rel):
    is_html = path.lower().endswith('.html')
    try:
        with open(path, encoding='utf-8', errors='replace') as fh:
            raw = fh.read()
    except OSError:
        return []
    text = visible_text(raw, is_html)

    seen, findings = set(), []
    for rx in ABSENCE_RE:
        for m in rx.finditer(text):
            key = (max(0, m.start() // 200), m.group(0).lower())
            if key in seen:
                continue
            seen.add(key)
            lo = max(0, m.start() - SCOPE_WINDOW)
            hi = min(len(text), m.end() + SCOPE_WINDOW)
            window = text[lo:hi]
            if has_qualifier(window):
                continue
            findings.append({
                'kind': 'UNSCOPED_ABSENCE',
                'file': rel,
                'claim': m.group(0),
                'context': text[max(0, m.start() - 130):
                                min(len(text), m.end() + 200)].strip(),
            })
    return findings


def main():
    print('=' * 60)
    print('  ABSENCE-CLAIM SCOPE GATE')
    print('=' * 60)

    findings, scanned = [], 0
    for d in SCAN_DIRS:
        root = os.path.join(ROOT, d)
        if not os.path.isdir(root):
            continue
        for dirpath, _dirs, files in os.walk(root):
            for fn in sorted(files):
                if not fn.lower().endswith(SCAN_EXT):
                    continue
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, ROOT).replace(os.sep, '/')
                scanned += 1
                findings.extend(scan_file(full, rel))

    result = {
        'audit': 'absence_claim_scope',
        'run_date': date.today().isoformat(),
        'files_scanned': scanned,
        'scope_window_chars': SCOPE_WINDOW,
        'findings': findings,
    }
    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, 'w', encoding='utf-8') as fh:
        json.dump(result, fh, indent=2)

    print(f'  Files scanned: {scanned}')
    print(f'  Report: {os.path.relpath(REPORT, ROOT)}')

    if not findings:
        print('\n  [OK] every absence claim declares the search that produced it.')
        return 0

    print(f'\n  [FAIL] {len(findings)} unscoped absence claim(s):')
    for f in findings:
        print(f'\n   {f["file"]}')
        print(f'     claim: "{f["claim"]}"')
        print(f'     ...{f["context"][:230]}...')
    print('\n  An empty result set is a fact about a query, not about the world.')
    print('  State the scope, or state a claim the search can support.')
    return 1


if __name__ == '__main__':
    sys.exit(main())
