#!/usr/bin/env python3
"""Publish the markdown reports the hub advertises -> docs/Reports/.

WHY THIS EXISTS
---------------
docs/index.html has carried two cards marked `status live` / "Available" since
the site was built:

    Literature Gap Analysis  -> Analysis/Results/literature_gap_report.md
    Publication Monitor      -> Analysis/Results/pubmed_recent_summary.md

Neither has ever been servable. docs/ is the Pages publish root, so those
page-relative hrefs resolve to docs/Analysis/Results/..., a directory that has
never existed. Measured 2026-09-04 by audit_published_links.py: 38 of the 40
relative links on the hub resolve; these two are the exceptions, and both are
the ones a reader is invited to click.

This is the 2026-08-16 dashboard-staleness defect in its markdown form.
sync_docs_dashboards.py copies *.html only, so no publisher ever looked at
these two files.

SCOPE - WHY ONLY TWO FILES
--------------------------
Analysis/Results holds 257 markdown files. 255 are dated run records - a
historical log, not a live claim - and stay unpublished, the same class
exclusion audit_markdown_citations.py makes. The two files here are in scope
for exactly one reason, and it is checked rather than asserted: the hub links
to them. The scope is DERIVED from docs/index.html at run time, so a report
added to or dropped from the hub changes what gets published without anyone
remembering to edit this list.

STALENESS IS PUBLISHED, NOT HIDDEN
----------------------------------
pubmed_recent_summary.md is titled "Recent Publications" with a "Lookback
period: 30 days" and was generated 2026-07-17 - 49 days before this script was
written. Fixing the link without saying so would take a page that 404s and
replace it with one that silently misleads, which is worse. Each published copy
therefore gets a provenance banner naming the source path and the generation
date it declares, so a reader can see the age of what they are reading.

Usage:
    python sync_docs_reports.py            # publish + verify
    python sync_docs_reports.py --check    # report drift only, no writes
"""
import os
import re
import sys
from datetime import date

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))
RESULTS_DIR = os.path.join(BASE_DIR, 'Analysis', 'Results')
DOCS_DIR = os.path.join(BASE_DIR, 'docs')
DST_DIR = os.path.join(DOCS_DIR, 'Reports')
INDEX = os.path.join(DOCS_DIR, 'index.html')

# The hub is the authority on what is advertised. Anything it links under
# Reports/ must exist in Analysis/Results with the same basename.
HUB_LINK_RE = re.compile(r'href="Reports/([A-Za-z0-9_\-.]+\.md)"')

# "**Generated:** 2026-09-03 07:17" / "**Generated:** 2026-07-17"
GENERATED_RE = re.compile(r'\*\*Generated:\*\*\s*([0-9]{4}-[0-9]{2}-[0-9]{2})')

BANNER = (
    '<!-- published by sync_docs_reports.py; do not edit here -->\n'
    '> **Published copy.** Source: `Analysis/Results/{name}`. '
    'This report declares a generation date of **{generated}**'
    '{age}. It is regenerated by the daily pipeline, not on page load.\n\n'
)


def advertised():
    if not os.path.exists(INDEX):
        return []
    with open(INDEX, encoding='utf-8', errors='replace') as fh:
        return sorted(set(HUB_LINK_RE.findall(fh.read())))


def read(path):
    with open(path, encoding='utf-8', errors='replace') as fh:
        return fh.read()


def published_form(name, source):
    m = GENERATED_RE.search(source)
    generated = m.group(1) if m else 'unstated'
    age = ''
    if m:
        try:
            days = (date.today() - date.fromisoformat(generated)).days
            if days >= 2:
                age = ', %d days ago' % days
        except ValueError:
            pass
    return BANNER.format(name=name, generated=generated, age=age) + source


def main():
    check_only = '--check' in sys.argv
    names = advertised()

    print('Publish advertised reports -> docs/Reports/')
    print('  hub        : %s' % os.path.relpath(INDEX, BASE_DIR))
    print('  advertised : %d report(s)' % len(names))

    if not names:
        print('\n[OK] the hub advertises no markdown reports; nothing to publish.')
        return 0

    stale, missing, ok, absent = [], [], [], []
    for name in names:
        src = os.path.join(RESULTS_DIR, name)
        dst = os.path.join(DST_DIR, name)
        if not os.path.exists(src):
            absent.append(name)
            continue
        want = published_form(name, read(src))
        if not os.path.exists(dst):
            missing.append((name, want))
        elif read(dst) != want:
            stale.append((name, want))
        else:
            ok.append(name)

    print('  stale=%d  missing=%d  in-sync=%d  source-absent=%d'
          % (len(stale), len(missing), len(ok), len(absent)))
    for name in absent:
        print('    ABSENT  %s - the hub links a report that does not exist' % name)

    if absent:
        print('\n[FAIL] the hub advertises %d report(s) with no source file.'
              % len(absent))
        return 1

    if check_only:
        for name, _ in stale:
            print('    STALE   %s' % name)
        for name, _ in missing:
            print('    MISSING %s' % name)
        if stale or missing:
            print('\n[FAIL] Published reports are behind their sources.')
            return 1
        print('\n[OK] Published reports match their sources.')
        return 0

    if not (stale or missing):
        print('\n[OK] Already in sync; nothing to publish.')
        return 0

    os.makedirs(DST_DIR, exist_ok=True)
    for name, want in stale + missing:
        with open(os.path.join(DST_DIR, name), 'w', encoding='utf-8') as fh:
            fh.write(want)

    for name, want in stale + missing:
        if read(os.path.join(DST_DIR, name)) != want:
            print('\n[FAIL] %s did not verify after publish.' % name)
            return 1

    print('\n[OK] Published %d report(s); all verified.' % len(stale + missing))
    return 0


if __name__ == '__main__':
    sys.exit(main())
